baseURL: 'https://hugo-ladder.pages.dev'
title: hugo-theme-dream
theme: hugo-theme-dream
license: MIT
licenselink: 'https://github.com/guangzhengli/hugo-theme-ladder/blob/master/LICENSE'
description: 'A fast, clean Hugo theme'
homepage: 'https://hugo-ladder.pages.dev'
defaultContentLanguage: 'zh'
googleAnalytics: G-7E4JNTL3ES
enableRobotsTXT: true
paginate: 10
hasCJKLanguage: true
copyright: "2023 GuangzhengLi All rights reserved"
Author:
  name: "Guangzheng Li"
  email: "iguangzhengli@gmail.com"
params:
  brand: HOME
  avatarURL: /images/avatar.png
  author: Hugo Ladder
  authorDescription: A clean, fast hugo theme focused on Reading
  info: Build a free and beautiful blog site to record your thoughts and increase your influence
  favicon: /images/avatar.ico
